cloud:
  aws:
    credentials:
      accessKey: ${S3_AccessKey}
      secretKey: ${S3_SecretKey}
    s3:
      bucket: ${S3_BucketName}
    #      bucket: ${bucket}
    region:
      static:
        ${S3_Region}
    stack:
      auto:
        false

CloudFrontURL: ${CloudFrontURL}